### ISSUE TITLE
Question: Image process flow

### ISSUE THREAD

**Issue by Vmadmax** [mowoe/heartbeat#2]
Unfortunately I have not yet fully understood the whole process based on the documentation.
Can you explain a litte bit more some sections?

For example what is "Request Work" for?

best regards

**Comment by mowoe** [comment]
The current Idea is, that Images can get submitted to heartbeat and are only stored on disk and database. Because you cant easily scale up CPU Power when more and more requests come in, you have a seperate "worker", that just calls an API endpoint, then downloads the image, does face recognition on it, and then submits the mathematical representation of the faces back to heartbeat. This way you can easily get an asynchronous task management, split up on to seperate machines. 

I will shortly rework the whole documentation, i hope it gets more clear then.
If you have any further question, feel free to write them into this issue.

**Comment by Vmadmax** [comment]
Hi @mowoe,
thanks for your quick response.
It's a good idea to split the workload. Is there a working version, or it's full work in progress?

**Comment by mowoe** [comment]
Hi,

there is a working version:
**[heartbeat.mowoe.com](https://heartbeat.mowoe.com)**
It has a database of roughly 400k images which come from a web crawler and an Instagram crawler. An easy way to test heartbeat, is to upload an image of **Angela Merkel**, it should give you 5 results (there are more, but 5 is currently the limit for display). Just go on the url and click start and you will be guided through the process (some of it is still in german). On the results page you can hover over the images to see where they came from. "heartbeat-crawler" means it came from my web crawler, "instagram" is obvious and "unknown" usually means, that the image was manually uploaded. You can do that via /upload_new. But it will take some time before this image will then be displayed as a result, as it needs to be processed.
Hope this helps!

**Comment by Vmadmax** [comment]
Hi,
this is exactly how I imagined it could be. 
It's working great.

Is your website up to date with the git project, so I can try a working version by myself?

**Comment by mowoe** [comment]
It is currently up to date, but it isnt deployed automatically, though i deploy ~once a a day when new changes are made. However the docker container is automatically built.
I dont fully understand your question, do you want to deploy a version by yourself or build something else?
Hope this helps anyway though!

**Comment by Vmadmax** [comment]
Hi @mowoe,
I have one more question about the flowchart.

Is "Phase 2: The Worker downloads the Image from the Server via the requested id." implemented yet? Or do I have to do this through a third application?

Max

**Comment by mowoe** [comment]
Hi,
I have a script, that is not published, as it is **really** shitty. It is multithreaded and thus relatively efficient. I cant provide any documentation for it, but I am sure you can figure out, what it does. Script is here (sorry for this mess):
[script](http://mowoe.com/face_encoding_example_worker.py)

PS: this whole project is not really in a stage, in which you could easily deploy it on your own, since everything is a huge mess and the documentation is not up to date and is missing huge parts. **But** if you have any questions you can contact me, either here, via twitter or any other communication service :)

**Comment by Vmadmax** [comment]
Hi,
thanks for your fast reply.

Sorry... I didn't see this file in the example folder. It works very well.

**Comment by mowoe** [comment]
@Vmadmax  please look into the updated readme. Especially [creating-the-face-recognition-model](https://github.com/mowoe/heartbeat#creating-the-face-recognition-model) and [the new default docker command](https://github.com/mowoe/heartbeat#the-easiest-way-to-deploy-heartbeat-is-by-using-docker). As I also have updated the docker container, please ensure that you pull the newest version, if you try to run heartbeat via docker.

**Comment by mowoe** [comment]
The Readme is updated now and it should be pretty self-explanatory. The Setup guide is now actually usable :)
